/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendapatan;

import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class form extends javax.swing.JFrame {

    int id;

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
        tanggal();
        table();
        tampildata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        laporan = new javax.swing.JButton();
        pendapatan = new javax.swing.JButton();
        pengeluaran = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        bonus = new javax.swing.JButton();
        gaji = new javax.swing.JButton();
        pegawai = new javax.swing.JButton();
        dash = new javax.swing.JButton();
        ket = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        masuktanggal = new javax.swing.JTextField();
        plhtanggal = new com.toedter.calendar.JDateChooser();
        txtjumlah = new javax.swing.JTextField();
        tglatas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardat = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 449));
        setMinimumSize(new java.awt.Dimension(800, 449));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 200, 530, 180);

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/laporan.png"))); // NOI18N
        getContentPane().add(laporan);
        laporan.setBounds(20, 345, 150, 25);

        pendapatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pendapatan.png"))); // NOI18N
        getContentPane().add(pendapatan);
        pendapatan.setBounds(20, 305, 150, 25);

        pengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pengeluaran.png"))); // NOI18N
        getContentPane().add(pengeluaran);
        pengeluaran.setBounds(20, 265, 150, 25);

        minus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        getContentPane().add(minus);
        minus.setBounds(20, 230, 150, 25);

        bonus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bonus.png"))); // NOI18N
        getContentPane().add(bonus);
        bonus.setBounds(20, 193, 150, 25);

        gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gaji.png"))); // NOI18N
        getContentPane().add(gaji);
        gaji.setBounds(20, 155, 150, 25);

        pegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pegawai.png"))); // NOI18N
        getContentPane().add(pegawai);
        pegawai.setBounds(20, 115, 150, 25);

        dash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dash.png"))); // NOI18N
        getContentPane().add(dash);
        dash.setBounds(20, 80, 150, 25);
        getContentPane().add(ket);
        ket.setBounds(233, 155, 200, 40);

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Keterangan :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(233, 140, 80, 14);

        masuktanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                masuktanggalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                masuktanggalKeyReleased(evt);
            }
        });
        getContentPane().add(masuktanggal);
        masuktanggal.setBounds(530, 170, 150, 25);
        getContentPane().add(plhtanggal);
        plhtanggal.setBounds(530, 107, 230, 25);
        getContentPane().add(txtjumlah);
        txtjumlah.setBounds(230, 107, 230, 25);

        tglatas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tglatas.setForeground(new java.awt.Color(153, 153, 153));
        tglatas.setText("Tanggal");
        getContentPane().add(tglatas);
        tglatas.setBounds(220, 20, 220, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biru.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 20, 220, 20);

        cardat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caridata.png"))); // NOI18N
        cardat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardatActionPerformed(evt);
            }
        });
        getContentPane().add(cardat);
        cardat.setBounds(685, 170, 75, 25);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        getContentPane().add(logout);
        logout.setBounds(15, 400, 160, 35);

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(440, 385, 75, 25);

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(524, 385, 75, 25);

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hapus.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(605, 385, 75, 25);

        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/simpan.png"))); // NOI18N
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan);
        simpan.setBounds(685, 385, 75, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pendapatan - Jadi.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masuktanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_masuktanggalKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_masuktanggalKeyPressed
    private void tampildata() {
        try
        {
            Object[] judul_kolom =
            {
                "Id Pendapatan", "Keterangan Pendapatan", "Jumlah Pendapatan", "Tanggal Pendapatan"
            };
            DefaultTableModel tabModel = new DefaultTableModel(null, judul_kolom);
            Table1.setModel(tabModel);

            java.sql.Connection conn = (Connection) Config.foderoDB();
            java.sql.Statement stm = conn.createStatement();
            tabModel.getDataVector().removeAllElements();

            java.sql.ResultSet rs = stm.executeQuery("SELECT * from pendapatan ");
            while (rs.next())
            {
                Object[] data =
                {
                    //rs.getString("No."),
                    rs.getString("Id Pendapatan"),
                    rs.getString("Keterangan Pendapatan"),
                    rs.getString("Jumlah Pendapatan"),
                    rs.getString("Tanggal Pendapatan"),
                };
                tabModel.addRow(data);
            }
        } catch (Exception ex)
        {
            System.err.println(ex.getMessage());
        }
    }

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(plhtanggal.getDate()));
        try
        {
            String sql = "INSERT INTO pendapatan (id_pendapatan, keterangan_pendapatan,jumlah_pendapatan,tanggal_pemasukan)" + "VALUES"
                    + "(null, '" + ket.getText() + "','" + txtjumlah.getText() + "',now())";
            java.sql.Connection conn = (Connection) Config.foderoDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        table();
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus data ?", "DELETE", JOptionPane.YES_NO_OPTION);
        if (opsi == 0)
        {
            String tampilan = "yyyy-MM-dd";
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            String tanggal = String.valueOf(fm.format(plhtanggal.getDate()));
            try
            {
                String sql = "DELETE FROM pendapatan WHERE id_pendapatan = '" + id + "'";
                java.sql.Connection conn = (Connection) Config.foderoDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        table();
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(plhtanggal.getDate()));
        try
        {
            String sql = "UPDATE pendapatan SET keterangan_pendapatan= '" + ket.getText() + "',jumlah_pendapatan= " + txtjumlah.getText() + ", tanggal_pemasukan = '" + tanggal + "' where id_pendapatan = " + id;
            java.sql.Connection conn = (Connection) Config.foderoDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Data berhasil di edit");
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        table();
    }//GEN-LAST:event_editActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        int baris = Table1.rowAtPoint(evt.getPoint());
        String keterangan = Table1.getValueAt(baris, 2).toString();
        ket.setText(keterangan);
        String jumlah = Table1.getValueAt(baris, 3).toString();
        txtjumlah.setText(jumlah);
//       String date = Table1.getValueAt(baris, 4).toString();
        Date date = null;
        try
        {
            date = new SimpleDateFormat("yyyy-MM-dd").parse(Table1.getValueAt(baris, 4).toString());
        } catch (ParseException ex)
        {
            Logger.getLogger(formpendapatan.class.getName()).log(Level.SEVERE, null, ex);
        }
        plhtanggal.setDate(date);
        id = Integer.valueOf(Table1.getValueAt(baris, 1).toString());
    }//GEN-LAST:event_Table1MouseClicked

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txtjumlah.setText(null);
        ket.setText(null);
        plhtanggal.setDate(null);
    }//GEN-LAST:event_clearActionPerformed

    private void cardatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardatActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(plhtanggal.getDate()));
        try
        {
            Object[] judul_kolom =
            {
                "Id Pendapatan", "Keterangan Pendapatan", "Jumlah Pendapatan", "Tanggal Pendapatan"
            };
            DefaultTableModel tabModel = new DefaultTableModel(null, judul_kolom);
            Table1.setModel(tabModel);

            java.sql.Connection conn = (Connection) Config.foderoDB();
            java.sql.Statement stm = conn.createStatement();
            tabModel.getDataVector().removeAllElements();

            java.sql.ResultSet rs = stm.executeQuery("SELECT * from pendapatan where  tanggal_pemasukan '%" + tanggal + "'%");
            while (rs.next())
            {
                Object[] data =
                {
                    //rs.getString("No."),
                    rs.getString("Id Pendapatan"),
                    rs.getString("Keterangan Pendapatan"),
                    rs.getString("Jumlah Pendapatan"),
                    rs.getString("Tanggal Pendapatan"),
                };
                tabModel.addRow(data);
            }
        } catch (Exception ex)
        {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_cardatActionPerformed

    private void masuktanggalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_masuktanggalKeyReleased
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(plhtanggal.getDate()));
        String key = masuktanggal.getText();
        System.out.println(tanggal);
        if (key != "")
        {
            cardat(tanggal);
        } else
        {
            tampildata();
        }
    }//GEN-LAST:event_masuktanggalKeyReleased
    private void tanggal() {
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat spdfmt = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
        String tanggal = spdfmt.format(tglsekarang);
        tglatas.setText(tanggal);
    }

    private void table() {
        DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("No.");
        tbl.addColumn("Id Pendapatan");
        tbl.addColumn(("Keterangan Pendapatan"));
        tbl.addColumn("Jumlah Pendapatan");
        tbl.addColumn("Tanggal Pendapatan");
        try
        {
            int no = 1;
            String sql = "SELECT * FROM pendapatan";
            java.sql.Connection conn = (Connection) Config.foderoDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);
            while (rs.next())
            {
                tbl.addRow(new Object[]
                {
                    no++,
                    rs.getString("id_pendapatan"),
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3)
                });
            }
            Table1.setModel(tbl);

        } catch (SQLException e)
        {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton bonus;
    private javax.swing.JButton cardat;
    private javax.swing.JButton clear;
    private javax.swing.JButton dash;
    private javax.swing.JButton edit;
    private javax.swing.JButton gaji;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ket;
    private javax.swing.JButton laporan;
    private javax.swing.JButton logout;
    private javax.swing.JTextField masuktanggal;
    private javax.swing.JButton minus;
    private javax.swing.JButton pegawai;
    private javax.swing.JButton pendapatan;
    private javax.swing.JButton pengeluaran;
    private com.toedter.calendar.JDateChooser plhtanggal;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel tglatas;
    private javax.swing.JTextField txtjumlah;
    // End of variables declaration//GEN-END:variables

    private void cardat(String key) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
