/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop_project;

import java.awt.print.PrinterException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.MessageFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JTable;
import static workshop_project.master_pegawai.getDate;

/**
 *
 * @author Tole
 */
public class LaporanForm extends javax.swing.JFrame {

    ArrayList<Integer> total = new ArrayList<Integer>();
    Utils util = new Utils();

    /**
     * Creates new form LaporanForm
     */
    public LaporanForm() throws SQLException {
        initComponents();
        name.setText(util.nama);
        nik.setText(util.nik);
        tanggal.setText(getDate());
        try {
            jLabel6.setText("Saldo: Rp. " + Utils.getSaldo());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e + "ERror");
        }
    }

    boolean val() {
        if (jDateChooser1.getDate().after(jDateChooser2.getDate())) {
            JOptionPane.showMessageDialog(null, "Tanggal awal tidak boleh lebih besar dari tanggal akhir!", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    int sum() {
        int s = 0;
        for (int i = 0; i < total.size(); i++) {
            s += total.get(i);
        }
        return s;
    }

    String rupiah(int num) {
        double a = Double.valueOf(String.valueOf(num));
        Locale localeID = new Locale("in", "ID");
        NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);

        //merubah mendari 10.000.000.000
        NumberFormat nf = NumberFormat.getNumberInstance(new Locale("in", "ID"));

        return String.valueOf(nf.format(a));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        m_dashboard = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        m_pegawai = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        m_gaji = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        m_bonus = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        m_minus = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        m_pengeluaran = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        m_pendapatan = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        m_laporan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        tanggal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Lexend", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(114, 114, 114));
        jLabel6.setText("saldo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 100, 180, 20);

        m_dashboard.setBackground(new java.awt.Color(244, 244, 244));
        m_dashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_dashboardMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(114, 114, 114));
        jLabel10.setText("Dashboard");

        javax.swing.GroupLayout m_dashboardLayout = new javax.swing.GroupLayout(m_dashboard);
        m_dashboard.setLayout(m_dashboardLayout);
        m_dashboardLayout.setHorizontalGroup(
            m_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_dashboardLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel10)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        m_dashboardLayout.setVerticalGroup(
            m_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_dashboard);
        m_dashboard.setBounds(10, 150, 170, 30);

        m_pegawai.setBackground(new java.awt.Color(244, 244, 244));
        m_pegawai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_pegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_pegawaiMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(114, 114, 114));
        jLabel11.setText("Pegawai");

        javax.swing.GroupLayout m_pegawaiLayout = new javax.swing.GroupLayout(m_pegawai);
        m_pegawai.setLayout(m_pegawaiLayout);
        m_pegawaiLayout.setHorizontalGroup(
            m_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_pegawaiLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel11)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        m_pegawaiLayout.setVerticalGroup(
            m_pegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_pegawaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_pegawai);
        m_pegawai.setBounds(10, 190, 170, 30);

        m_gaji.setBackground(new java.awt.Color(244, 244, 244));
        m_gaji.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_gaji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_gajiMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(114, 114, 114));
        jLabel12.setText("Gaji");

        javax.swing.GroupLayout m_gajiLayout = new javax.swing.GroupLayout(m_gaji);
        m_gaji.setLayout(m_gajiLayout);
        m_gajiLayout.setHorizontalGroup(
            m_gajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_gajiLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel12)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        m_gajiLayout.setVerticalGroup(
            m_gajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_gajiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_gaji);
        m_gaji.setBounds(10, 230, 170, 30);

        m_bonus.setBackground(new java.awt.Color(244, 244, 244));
        m_bonus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_bonus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_bonus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_bonusMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(114, 114, 114));
        jLabel13.setText("Bonus");

        javax.swing.GroupLayout m_bonusLayout = new javax.swing.GroupLayout(m_bonus);
        m_bonus.setLayout(m_bonusLayout);
        m_bonusLayout.setHorizontalGroup(
            m_bonusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_bonusLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel13)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        m_bonusLayout.setVerticalGroup(
            m_bonusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_bonusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_bonus);
        m_bonus.setBounds(10, 270, 170, 30);

        m_minus.setBackground(new java.awt.Color(244, 244, 244));
        m_minus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_minusMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(114, 114, 114));
        jLabel14.setText("Minus");

        javax.swing.GroupLayout m_minusLayout = new javax.swing.GroupLayout(m_minus);
        m_minus.setLayout(m_minusLayout);
        m_minusLayout.setHorizontalGroup(
            m_minusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_minusLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel14)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        m_minusLayout.setVerticalGroup(
            m_minusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_minusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_minus);
        m_minus.setBounds(10, 310, 170, 30);

        m_pengeluaran.setBackground(new java.awt.Color(244, 244, 244));
        m_pengeluaran.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_pengeluaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_pengeluaranMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(114, 114, 114));
        jLabel15.setText("Pengeluaran");

        javax.swing.GroupLayout m_pengeluaranLayout = new javax.swing.GroupLayout(m_pengeluaran);
        m_pengeluaran.setLayout(m_pengeluaranLayout);
        m_pengeluaranLayout.setHorizontalGroup(
            m_pengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_pengeluaranLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel15)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        m_pengeluaranLayout.setVerticalGroup(
            m_pengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_pengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_pengeluaran);
        m_pengeluaran.setBounds(10, 350, 170, 30);

        m_pendapatan.setBackground(new java.awt.Color(244, 244, 244));
        m_pendapatan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_pendapatan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        m_pendapatan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_pendapatanMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(114, 114, 114));
        jLabel16.setText("Pendapatan");

        javax.swing.GroupLayout m_pendapatanLayout = new javax.swing.GroupLayout(m_pendapatan);
        m_pendapatan.setLayout(m_pendapatanLayout);
        m_pendapatanLayout.setHorizontalGroup(
            m_pendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_pendapatanLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel16)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        m_pendapatanLayout.setVerticalGroup(
            m_pendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_pendapatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_pendapatan);
        m_pendapatan.setBounds(10, 390, 170, 30);

        m_laporan.setBackground(new java.awt.Color(167, 191, 192));
        m_laporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel17.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(114, 114, 114));
        jLabel17.setText("Laporan");

        javax.swing.GroupLayout m_laporanLayout = new javax.swing.GroupLayout(m_laporan);
        m_laporan.setLayout(m_laporanLayout);
        m_laporanLayout.setHorizontalGroup(
            m_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_laporanLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel17)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        m_laporanLayout.setVerticalGroup(
            m_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(m_laporan);
        m_laporan.setBounds(10, 430, 170, 30);

        jPanel14.setBackground(new java.awt.Color(252, 102, 103));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("LOGOUT");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(31, 31, 31))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap())
        );

        getContentPane().add(jPanel14);
        jPanel14.setBounds(20, 470, 150, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 114, 114));
        jLabel1.setText("Tanggal Awal:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 119, 20);

        jButton2.setBackground(new java.awt.Color(255, 149, 51));
        jButton2.setText("Export Data");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(460, 320, 100, 30);

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(114, 114, 114));
        jLabel2.setText("Tanggal Akhir:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 20, 119, 20);

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(114, 114, 114));
        jLabel5.setText("Total :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 70, 240, 20);

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(114, 114, 114));
        jLabel3.setText("Tipe:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 40, 20);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gaji", "Pengeluaran", "Pendapatan" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(20, 90, 220, 30);

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(114, 114, 114));
        jLabel4.setText("Rp.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 90, 220, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 540, 180);

        jButton1.setText("Tampilkan Data");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 320, 150, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(20, 40, 220, 28);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(340, 40, 220, 28);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 130, 580, 360);

        jPanel4.setBackground(new java.awt.Color(239, 245, 245));

        tanggal.setFont(new java.awt.Font("Lexend", 0, 13)); // NOI18N
        tanggal.setForeground(new java.awt.Color(114, 114, 114));
        tanggal.setText("Tanggal");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(tanggal))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(200, 100, 90, 20);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 120, 190, 390);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        name.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(114, 114, 114));
        name.setText("Nama Pegawai");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel15);
        jPanel15.setBounds(40, 90, 150, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/workshop_project/Laporan - Jadi_800x449.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 80, 800, 440);

        jPanel2.setBackground(new java.awt.Color(239, 245, 245));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 80);

        jPanel3.setBackground(new java.awt.Color(239, 245, 245));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 520, 800, 80);

        nik.setText("jLabel7");
        getContentPane().add(nik);
        nik.setBounds(510, 100, 39, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (val()) {
            java.sql.Date awal, akhir;
            String tipe, query;
            int i = 1, jumlah = 0;
            DefaultTableModel dt = new DefaultTableModel();
            awal = new java.sql.Date(jDateChooser1.getDate().getTime());
            akhir = new java.sql.Date(jDateChooser2.getDate().getTime());
            tipe = jComboBox1.getSelectedItem().toString();
            if (tipe == "Gaji") {
                total.clear();
                query = "select qty, pegawai.nama_pegawai, pengeluaran.nik, pengeluaran.jumlah_pengeluaran, monthname(tanggal_pengeluaran) as bulan, day(tanggal_pengeluaran) as tanggal, mst_minus.nama_minus from pengeluaran "
                        + "join gaji on gaji.id_pengeluaran = pengeluaran.id_pengeluaran "
                        + "join pegawai on pegawai.nik = pengeluaran.nik "
                        + "join mst_minus on gaji.id_minus = mst_minus.id_minus "
                        + "where jenis_pengeluaran = '" + tipe + "' and tanggal_pengeluaran >= '" + awal + "' and tanggal_pengeluaran <= '" + akhir + "'";
                String query1 = "select qty, pegawai.nama_pegawai, pengeluaran.nik, pengeluaran.jumlah_pengeluaran, monthname(tanggal_pengeluaran) as bulan, day(tanggal_pengeluaran) as tanggal, mst_bonus.nama_bonus from pengeluaran "
                        + "join gaji on gaji.id_pengeluaran = pengeluaran.id_pengeluaran "
                        + "join mst_bonus on gaji.id_bonus = mst_bonus.id_bonus "
                        + "join pegawai on pegawai.nik = pengeluaran.nik "
                        + "where jenis_pengeluaran = '" + tipe + "' and tanggal_pengeluaran >= '" + awal + "' and tanggal_pengeluaran <= '" + akhir + "'";
                String query2 = "select pegawai.nama_pegawai, pengeluaran.nik, pengeluaran.jumlah_pengeluaran, monthname(tanggal_pengeluaran) as bulan, day(tanggal_pengeluaran) as tanggal from pengeluaran "
                        + "join pegawai on pegawai.nik = pengeluaran.nik "
                        + "where jenis_pengeluaran = '" + tipe + "' and tanggal_pengeluaran >= '" + awal + "' and tanggal_pengeluaran <= '" + akhir + "'";
                dt.addColumn("Nama Pegawai");
                dt.addColumn("Tanggal");
                dt.addColumn("Nominal");
                dt.addColumn("Bonus");
                dt.addColumn("Minus");
                dt.addColumn("Qty");
                jTable1.setModel(dt);
                try {
                    Statement st = (Statement) Utils.foderoDB().createStatement();
                    ResultSet rs = st.executeQuery(query);
                    Statement st1 = (Statement) Utils.foderoDB().createStatement();
                    ResultSet rs1 = st1.executeQuery(query1);
                    Statement st2 = (Statement) Utils.foderoDB().createStatement();
                    ResultSet rs2 = st2.executeQuery(query2);
                    Statement st3 = (Statement) Utils.foderoDB().createStatement();
                    ResultSet rs3 = st3.executeQuery("select sum(jumlah_pengeluaran) as jumlah from pengeluaran where jenis_pengeluaran = '" + tipe + "' and tanggal_pengeluaran >= '" + awal + "' and tanggal_pengeluaran <= '" + akhir + "'");
                    if (rs3.next()) {
                        jumlah = Integer.parseInt(rs3.getString("jumlah"));
                    }
                    while (rs.next()) {
                        dt.addRow(new Object[]{
                            rs.getString("nama_pegawai"),
                            rs.getString("tanggal") + " " + rs.getString("bulan"),
                            "Rp." + rupiah(Integer.valueOf(rs.getString("jumlah_pengeluaran"))),
                            "",
                            rs.getString("nama_minus"),
                            rs.getString("qty")
                        });
                        total.add(Integer.valueOf(rs.getString("jumlah_pengeluaran")));
                    }
                    while (rs1.next()) {
                        dt.addRow(new Object[]{
                            rs1.getString("nama_pegawai"),
                            rs1.getString("tanggal") + " " + rs1.getString("bulan"),
                            "Rp." + rupiah(Integer.valueOf(rs1.getString("jumlah_pengeluaran"))),
                            rs1.getString("nama_bonus"),
                            "",
                            rs1.getString("qty")
                        });
                    }
                    while (rs2.next()) {
                        dt.addRow(new Object[]{
                            rs2.getString("nama_pegawai"),
                            rs2.getString("tanggal") + " " + rs2.getString("bulan"),
                            "Rp." + rupiah(Integer.valueOf(rs2.getString("jumlah_pengeluaran"))),});
                    }

                    jTable1.setModel(dt);
                    jLabel4.setText("Rp. " + rupiah(jumlah));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e, "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
                }

            } else if(tipe == "Pengeluaran") {
                total.clear();
                query = "select pengeluaran.keterangan_pengeluaran, pegawai.nama_pegawai, pengeluaran.nik, pengeluaran.jumlah_pengeluaran, tanggal_pengeluaran as tanggal from pengeluaran "
                        + "left join gaji on gaji.id_pengeluaran = pengeluaran.id_pengeluaran "
                        + "join pegawai on pegawai.nik = pengeluaran.nik "
                        + "where jenis_pengeluaran = 'Barang Pokok' or jenis_pengeluaran = 'Lain-Lain' and tanggal_pengeluaran >= '" + awal + "' and tanggal_pengeluaran <= '" + akhir + "'";
                dt.addColumn("Nama Pegawai");
                dt.addColumn("Tanggal");
                dt.addColumn("Nominal");
                dt.addColumn("Keterangan");
                jTable1.setModel(dt);
                try {
                    Statement st = (Statement) Utils.foderoDB().createStatement();
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        dt.addRow(new Object[]{
                            rs.getString("nama_pegawai"),
                            rs.getString("tanggal"),
                            "Rp." + rupiah(Integer.valueOf(rs.getString("jumlah_pengeluaran"))),
                            rs.getString("keterangan_pengeluaran"),});
                        total.add(Integer.valueOf(rs.getString("jumlah_pengeluaran")));

                        jTable1.setModel(dt);
                    }
                    jLabel4.setText("Rp. " + rupiah(sum()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e + "Error", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            } else if (tipe == "Pendapatan") {
                query = "select pendapatan.*, pegawai.nama_pegawai from pendapatan join pegawai on pegawai.nik = pendapatan.nik "
                        + "where tanggal_pemasukan >= '" + awal + "' and tanggal_pemasukan <= '" + akhir + "'";
                dt.addColumn("Nama Pegawai");
                dt.addColumn("Tanggal");
                dt.addColumn("Nominal");
                dt.addColumn("Keterangan");
                jTable1.setModel(dt);
                try {
                    Statement st = (Statement) Utils.foderoDB().createStatement();
                    ResultSet rs = st.executeQuery(query);
                    while (rs.next()) {
                        dt.addRow(new Object[]{
                            rs.getString("nama_pegawai"),
                            rs.getString("tanggal_pemasukan"),
                            "Rp." + rupiah(Integer.valueOf(rs.getString("jumlah_pendapatan"))),
                            rs.getString("keterangan_pemasukan"),});
                        total.add(Integer.valueOf(rs.getString("jumlah_pendapatan")));

                        jTable1.setModel(dt);
                    }
                    jLabel4.setText("Rp. " + rupiah(sum()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e + "Error", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Laporan Pengeluaran Home Fodero");
        MessageFormat footer = new MessageFormat("");
        try {
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.PORTRAIT);
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, set, true);
            JOptionPane.showMessageDialog(null, "Sukses", "Berhasil Mencetak Laporan", JOptionPane.INFORMATION_MESSAGE);
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan", e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void m_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_pegawaiMouseClicked
        try {
            String sql = "SELECT * FROM pegawai WHERE nik = '" + nik.getText() + "'";
            Connection conn = (Connection) Workshop_project.foderoDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
            if (rs.getString("tipe").equals("karyawan")) {
                JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini !");
            } else {
                try {
                    // TODO add your handling code here:
                    new master_pegawai().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_m_pegawaiMouseClicked

    private void m_bonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_bonusMouseClicked
        try {
            String sql = "SELECT * FROM pegawai WHERE nik = '" + nik.getText() + "'";
            Connection conn = (Connection) Workshop_project.foderoDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
            if (rs.getString("tipe").equals("karyawan")) {
                JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini !");
            } else {
                try {
                    // TODO add your handling code here:
                    new MasterBonus().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_m_bonusMouseClicked

    private void m_minusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_minusMouseClicked
        try {
            String sql = "SELECT * FROM pegawai WHERE nik = '" + nik.getText() + "'";
            Connection conn = (Connection) Workshop_project.foderoDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
            if (rs.getString("tipe").equals("karyawan")) {
                JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini !");
            } else {
                try {
                    // TODO add your handling code here:
                    new MasterMinus().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_m_minusMouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void m_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_dashboardMouseClicked
        try {
            // TODO add your handling code here:
            new DashboardForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_m_dashboardMouseClicked

    private void m_pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_pengeluaranMouseClicked
        try {
            // TODO add your handling code here:
            new PengeluaranForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_m_pengeluaranMouseClicked

    private void m_gajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_gajiMouseClicked
        try {
            String sql = "SELECT * FROM pegawai WHERE nik = '" + nik.getText() + "'";
            Connection conn = (Connection) Workshop_project.foderoDB();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery(sql);
            rs.next();
            if (rs.getString("tipe").equals("karyawan")) {
                JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses menu ini !");
            } else {
                try {
                    // TODO add your handling code here:
                    new PembayaranGaji().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_m_gajiMouseClicked

    private void m_pendapatanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_pendapatanMouseClicked
        try {
            // TODO add your handling code here:
            new PendapatanForm().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_m_pendapatanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LaporanForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LaporanForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel m_bonus;
    private javax.swing.JPanel m_dashboard;
    private javax.swing.JPanel m_gaji;
    private javax.swing.JPanel m_laporan;
    private javax.swing.JPanel m_minus;
    private javax.swing.JPanel m_pegawai;
    private javax.swing.JPanel m_pendapatan;
    private javax.swing.JPanel m_pengeluaran;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nik;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables
}
